export const AuthConstants = {
	JWT_TOKEN: 'JWT_TOKEN'
}

export const DatabaseConstants = {
	DB_HOST: 'DB_HOST',
	DB_PORT: 'DB_PORT',
	DB_USERNAME: 'DB_USERNAME',
	DB_NAME: 'DB_NAME',
	DB_PASSWORD: 'DB_PASSWORD'
}

export const EmailConstants = {
	POSTMARK_SERVER_API_KEY: 'POSTMARK_SERVER_API_KEY',
	MAIL_SENDER_EMAIL: 'MAIL_SENDER_EMAIL',
	MAIL_SENDER_NAME: 'MAIL_SENDER_NAME',
	MAILJET_API_KEY_PUBLIC: 'MAILJET_API_KEY_PUBLIC',
	MAILJET_SECRET_KEY_PUBLIC: 'MAILJET_SECRET_KEY_PUBLIC'
}
